# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: event_postgres
    environment:
      POSTGRES_USER: event
      POSTGRES_PASSWORD: eventPassword
      POSTGRES_DB: event_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
